# Домашнее задание. Анализ табличных данных с Pandas

## Общие правила

Используйте:

```text
laptop.csv
```

Загрузите его через Pandas с кодировкой:

```text
windows-1251
```

Задачи решайте средствами Pandas, разобранными на занятии.

Не перебирайте строки DataFrame вручную через `for`.

> В примерах индекс DataFrame иногда не показан. Наличие индекса слева в вашем выводе не является ошибкой.

Задания 4–8 выполняются последовательно: созданные ранее столбцы используйте дальше, повторно создавать их не нужно.
Примеры вывода могут отличаться у вас от показанных тут ;-)

---

# Задание 1. Ноутбуки с Chrome OS

Найдите все ноутбуки с:

```text
OpSys = Chrome OS
```

Выведите количество моделей и первые 5 строк со столбцами:

```text
Company
Product
TypeName
OpSys
Price_euros
```

### Пример результата

```text
Количество: 27
```

```text
Company  Product              TypeName   OpSys      Price_euros
Acer     Chromebook C910-C2ST Notebook   Chrome OS       199.0
Lenovo   ThinkPad 13          Notebook   Chrome OS       459.9
Samsung  Chromebook 3         Netbook    Chrome OS       269.0
Google   Pixelbook (Core      Ultrabook  Chrome OS      2199.0
Google   Pixelbook (Core      Ultrabook  Chrome OS      1275.0
```

In [13]:
import pandas as pd

df = pd.read_csv('laptop.csv', encoding='windows-1251')
mask1 = df["OpSys"] == "Chrome OS"
hw1 = df[mask1]
print(f'Количество: {hw1.Company.count()}')
hw1[["Company","Product","TypeName","OpSys","Price_euros"]].head(5)
# hw1.count("laptop_ID")

Количество: 27

     Company               Product   TypeName      OpSys  Price_euros
290     Acer  Chromebook C910-C2ST   Notebook  Chrome OS        199.0
317   Lenovo           ThinkPad 13   Notebook  Chrome OS        459.9
430  Samsung          Chromebook 3    Netbook  Chrome OS        269.0
437   Google       Pixelbook (Core  Ultrabook  Chrome OS       2199.0
472   Google       Pixelbook (Core  Ultrabook  Chrome OS       1275.0



# Задание 2. Подбор ноутбука клиенту

Клиенту нужен ноутбук:

- `8GB` или `16GB` RAM;
- Windows 10;
- цена не выше `500` евро.

Определите количество вариантов и выведите первые 5:

```text
Company
Product
Ram
OpSys
Price_euros
```

### Пример результата

```text
Количество вариантов: 13
```

```text
Company  Product                                      Ram  OpSys       Price_euros
Acer     Aspire E5-475                                8GB  Windows 10       389.0
Dell     Inspiron 3567                                8GB  Windows 10       459.0
HP       15-BW094nd (A6-9220/8GB/128GB/W10)          8GB  Windows 10       445.9
HP       17-BS037cl (i3-6006U/8GB/1TB/W10)           8GB  Windows 10       489.0
Acer     ES1-523-84K7 (A8-7410/8GB/256GB/FHD/W10)    8GB  Windows 10       469.0
```

---

In [19]:
mask2 = (df["OpSys"] == "Windows 10") & (df["Price_euros"] < 500) & ((df["Ram"] == "8GB") | (df["Ram"] == "16GB"))
hw2 = df[mask2]
hw2[["Company","Product","TypeName","OpSys","Price_euros"]].head(5)

,Company,Product,TypeName,OpSys,Price_euros
74,Acer,Aspire E5-475,Notebook,Windows 10,389.0
175,Dell,Inspiron 3567,Notebook,Windows 10,459.0
256,HP,15-BW094nd (A6-9220/8GB/128GB/W10),Notebook,Windows 10,445.9
292,HP,17-BS037cl (i3-6006U/8GB/1TB/W10),Notebook,Windows 10,489.0
313,Acer,ES1-523-84K7 (A8-7410/8GB/256GB/FHD/W10),Notebook,Windows 10,469.0

# Задание 3. Самая маленькая диагональ

Определите минимальную диагональ экрана в наборе данных.

Выведите **все** ноутбуки с такой диагональю:

```text
Company
Product
TypeName
Inches
Price_euros
```

### Пример результата

```text
Минимальная диагональ: 10.1
Количество моделей: 4
```

```text
Company  Product    TypeName              Inches  Price_euros
Lenovo   Yoga Book  2 in 1 Convertible     10.1       319.00
Lenovo   Yoga Book  2 in 1 Convertible     10.1       646.27
Lenovo   Yoga Book  2 in 1 Convertible     10.1       549.00
Lenovo   Yoga Book  2 in 1 Convertible     10.1       479.00
```

---

In [34]:
hw3 = df['Inches'].min().astype(float)
print(f'Минимальная диагональ: {hw3}')
mask3 = df['Inches'] == hw3
hw3 = df[mask3]
print(f'Количество моделей: {hw3['Company'].count()}')
hw3[["Company","Product","TypeName","OpSys","Price_euros"]].head(5)

Минимальная диагональ: 10.1
Количество моделей: 4

     Company    Product            TypeName       OpSys  Price_euros
50    Lenovo  Yoga Book  2 in 1 Convertible     Android       319.00
1082  Lenovo  Yoga Book  2 in 1 Convertible  Windows 10       646.27
1114  Lenovo  Yoga Book  2 in 1 Convertible     Android       549.00
1126  Lenovo  Yoga Book  2 in 1 Convertible  Windows 10       479.00



# Задание 4. Тип экрана

Создайте столбец:

```text
Display_type
```

Правила:

```text
есть IPS Panel и Touchscreen -> IPS Touch
есть только Touchscreen      -> Touch
есть только IPS Panel        -> IPS
остальные                    -> Обычный
```

Логику вынесите в отдельную функцию.

Посчитайте количество ноутбуков каждого типа.


### Пример результата

```text
IPS Touch: 85
Touch: 107
IPS: 280
Обычный: 831
```

---

In [48]:
def add_columns(row):
    if row["ScreenResolution"].find("IPS Panel") != -1 and row["ScreenResolution"].find("Touchscreen") != -1:
        return 'IPS Touch'
    elif row["ScreenResolution"].find("Touchscreen") != -1:
        return 'Touch'
    elif row["ScreenResolution"].find("IPS Panel") != -1:
        return 'IPS'
    return 'Обычный'

hw4 = df.copy()

hw4["Display_type"] = df.apply(add_columns, axis=1)

print(f"IPS Touch: {hw4[hw4["Display_type"] == "IPS Touch"]["Ram"].count()}")
print(f"IPS Touch: {hw4[hw4["Display_type"] == "Touch"]["Ram"].count()}")
print(f"IPS Touch: {hw4[hw4["Display_type"] == "IPS"]["Ram"].count()}")
print(f"IPS Touch: {hw4[hw4["Display_type"] == "Обычный"]["Ram"].count()}")

IPS Touch: 85
IPS Touch: 107
IPS Touch: 280
IPS Touch: 831



# Задание 5. Недорогие трансформеры с IPS Touch

Используйте `Display_type` из задания 4.

Найдите ноутбуки:

```text
Display_type = IPS Touch
TypeName = 2 in 1 Convertible
Price_euros <= 1500
```

Отсортируйте по цене, а при одинаковой цене — по `laptop_ID`.

Выведите количество и первые 5 моделей.

### Пример результата

```text
Количество: 44
```

```text
laptop_ID  Company   Product                               Inches  Price_euros
436        Mediacom  FlexBook Edge                           11.6        299.0
51         Lenovo    Yoga Book                               10.1        319.0
567        Acer      Spin SP111-31                           11.6        349.0
626        Acer      CB5-132T-C9KK (N3160/4GB/32GB/Chrome   11.6        379.0
973        Acer      Chromebook C738T-C2EJ                   11.6        389.0
```

---

In [50]:
hw4[(hw4["Display_type"]=="IPS Touch") & (hw4["Price_euros"] < 500) & (hw4["TypeName"] == "2 in 1 Convertible")][["laptop_ID","Company","Product","Inches","Price_euros"]].sort_values(["Price_euros", "laptop_ID"], ascending=[True, False]).head(5)

,laptop_ID,Company,Product,Inches,Price_euros
429,436,Mediacom,FlexBook Edge,11.6,299.0
50,51,Lenovo,Yoga Book,10.1,319.0
560,567,Acer,Spin SP111-31,11.6,349.0
619,626,Acer,CB5-132T-C9KK (N3160/4GB/32GB/Chrome,11.6,379.0
959,973,Acer,Chromebook C738T-C2EJ,11.6,389.0



# Задание 6. Игровые ноутбуки с GTX 1060

Найдите модели:

```text
TypeName = Gaming
Gpu = Nvidia GeForce GTX 1060
диагональ не равна 17.3
цена <= 1800 евро
```

Отсортируйте по цене, затем по `laptop_ID`.

Выведите количество и первые 5 моделей.

### Пример результата

```text
Количество: 16
```

```text
laptop_ID  Company  Product                                   Inches  Price_euros
1143       Lenovo   Legion Y520-15IKBN                         15.6        989.0
516        Lenovo   Legion Y520-15IKBN                         15.6       1149.0
1222       Asus     FX502VM-DM105T (i7-6700HQ/8GB/1TB/GeForce 15.6       1169.0
1001       Lenovo   Legion Y520-15IKBN                         15.6       1189.0
95         Dell     Inspiron 7577                              15.6       1195.0
```

---

In [55]:

hw6 = df[(df['TypeName'] == 'Gaming') & (df['Gpu'] == 'Nvidia GeForce GTX 1060') & (df['Inches'] != 17.3) & (df['Price_euros'] <= 1800)]
print(f'Количество: {hw6.shape[0]}')
print(hw6[["laptop_ID","Company","Product","Inches","Price_euros"]].sort_values(by=['Price_euros', 'laptop_ID']).head(5))

Количество: 16
      laptop_ID Company                                    Product  Inches  \
1128       1143  Lenovo                         Legion Y520-15IKBN    15.6
509         516  Lenovo                         Legion Y520-15IKBN    15.6
1204       1222    Asus  FX502VM-DM105T (i7-6700HQ/8GB/1TB/GeForce    15.6
987        1001  Lenovo                         Legion Y520-15IKBN    15.6
93           95    Dell                              Inspiron 7577    15.6

      Price_euros
1128        989.0
509        1149.0
1204       1169.0
987        1189.0
93         1195.0


# Задания со звёздочкой ⭐

## Задание 7 ⭐. Тип накопителя

Создайте столбец:

```text
Storage_type
```

Правила:

```text
есть SSD и HDD -> SSD + HDD
есть SSD       -> SSD
есть HDD       -> HDD
остальные      -> Другое
```

После этого найдите модели:

```text
Storage_type = SSD + HDD
TypeName = Gaming
OpSys = Windows 10
Price_euros <= 1800
```

Отсортируйте по цене, затем по `laptop_ID`.

### Пример результата

```text
Количество: 82
```

Первые 5:

```text
laptop_ID  Company  Product                            Memory                Price_euros
1203       Asus     Rog GL552VW-DM201T                 256GB SSD + 1TB HDD        909.0
140        Asus     FX753VD-GC086T (i5-7300HQ/8GB/1TB 128GB SSD + 1TB HDD        938.0
22         Lenovo   Legion Y520-15IKBN                 128GB SSD + 1TB HDD        999.0
959        Lenovo   IdeaPad Y700-15ACZ                 512GB SSD + 1TB HDD        999.0
1246       Lenovo   IdeaPad Y700-15ISK                 128GB SSD + 1TB HDD       1029.0
```

In [59]:
def add_columns(row):
    if row["Memory"].find("SSD") != -1 and row["Memory"].find("HDD") != -1:
        return 'SSD + HDD'
    elif row["Memory"].find("SSD") != -1:
        return 'SSD'
    elif row["Memory"].find("HDD") != -1:
        return 'HDD'
    return 'Другое'

hw7 = df.copy()

hw7["Storage_type"] = df.apply(add_columns, axis=1)

hw71 = hw7[(hw7["TypeName"] == "Gaming") & (hw7["Storage_type"] == "SSD + HDD") & (hw7["OpSys"] == "Windows 10") & (hw7["Price_euros"] <= 1800)]
print(f'Количество: {hw71.shape[0]}')
hw71[["laptop_ID","Company","Product","TypeName","OpSys","Price_euros"]].sort_values(by=['Price_euros', 'laptop_ID']).head(5)

Количество: 82

,laptop_ID,Company,Product,TypeName,OpSys,Price_euros
1185,1203,Asus,Rog GL552VW-DM201T,Gaming,Windows 10,909.0
137,140,Asus,FX753VD-GC086T (i5-7300HQ/8GB/1TB,Gaming,Windows 10,938.0
21,22,Lenovo,Legion Y520-15IKBN,Gaming,Windows 10,999.0
945,959,Lenovo,IdeaPad Y700-15ACZ,Gaming,Windows 10,999.0
1228,1246,Lenovo,IdeaPad Y700-15ISK,Gaming,Windows 10,1029.0


## Задание 8 ⭐. Итоговый каталог

Используйте:

```text
Display_type
Storage_type
```

из заданий 4 и 7.

Отберите ноутбуки:

```text
Display_type = IPS
Storage_type = SSD + HDD
OpSys = Windows 10
1000 <= Price_euros <= 1600
```

Оставьте:

```text
laptop_ID
Company
Product
TypeName
Memory
Price_euros
Display_type
Storage_type
```

Отсортируйте:

1. по компании;
2. внутри компании — по цене от большей к меньшей;
3. при одинаковой цене — по `laptop_ID`.

Обновите индексы и сохраните результат:

```text
final_catalog.csv
```

без индекса DataFrame.

### Пример результата

```text
Количество: 33
```

Первые 5:

```text
laptop_ID  Company  Product                            TypeName  Price_euros
1014       Acer     Nitro 5                            Gaming        1260.0
1263       Asus     Rog GL553VE-FY052T                 Gaming        1600.0
1107       Asus     Rog GL702VM-GC354T                 Gaming        1599.0
90         Asus     FX503VM-E4007T (i7-7700HQ/16GB/1TB Gaming        1449.0
1124       Asus     Rog GL552VW-CN470T                 Gaming        1339.0
```

---

In [90]:
df = pd.read_csv('laptop.csv', encoding='windows-1251')
def add_columns(row):
    if row["Memory"].find("SSD") != -1 and row["Memory"].find("HDD") != -1:
        l1 = 'SSD + HDD'
    elif row["Memory"].find("SSD") != -1:
        l1 = 'SSD'
    elif row["Memory"].find("HDD") != -1:
        l1 = 'HDD'
    else:
        l1 = 'Другое'

    if row["ScreenResolution"].find("IPS Panel") != -1 and row["ScreenResolution"].find("Touchscreen") != -1:
        l2= 'IPS Touch'
    elif row["ScreenResolution"].find("Touchscreen") != -1:
        l2= 'Touch'
    elif row["ScreenResolution"].find("IPS Panel") != -1:
        l2= 'IPS'
    else:
        l2= 'Другое'
    return l1,l2


hw8 = df.copy()
hw8[["Storage_type","Display_type"]] = df.apply(add_columns, axis=1, result_type='expand')

hw8 = hw8[(hw8["TypeName"] == "Gaming") & (hw8["Storage_type"] == "SSD + HDD") & (hw8["OpSys"] == "Windows 10") & (hw8["Price_euros"] <= 1600)]
hw8 = hw8[["laptop_ID","Company","Product","TypeName","Memory","Price_euros","Display_type","Storage_type"]]
hw8.sort_values(by=["Company", "Price_euros", "laptop_ID"], inplace=True)
hw8.reset_index(drop=True, inplace=True)

hw8.to_csv("final_catalog.csv", index=False)